### PR TITLE
Support for A-Frame 0.7

### PR DESCRIPTION
**Pull request by UXVirtual**
There were some breaking changes in A-Frame 0.7 with recent releases of THREE.js which caused the canvas to be added to the DOM differently. This broke the existing method of adding event listeners to the scene. This PR resolves these issues and now binds to `renderstart` instead of `render-target-loaded`.

### CODE REVIEW

**Comment by timothy777** [comment]
@HAZARDU5 Thanks for the solution. But click events seems not working on Android browser.

**Comment by AndreaMonzini** [comment]
This is important PR because the component does not work work with the current A-Frame 0.7

**Comment by ngokevin** [comment]
A-Frame has this functionality built in. `cursor="rayOrigin: mouse"`.

**Comment by AndreaMonzini** [comment]
@ngokevin thank you ! i will try it!

**Comment by mayognaise** [comment]
I will close this PR as this feature is now available in A-Frame v0.6.1 by setting `<a-scene cursor="rayOrigin: mouse">`. 😄

**Pull request closed without merging**
