### PR TITLE
Updated to account for mouse offset on embed / resize / scroll

### PR DESCRIPTION
**Pull request by toychicken**
This should mean that the mouse-cursor will now work accurately on scenes embedded in pages. It swaps out the test for the window innerWidth & innerHeight, for the canvas dimensions - which in turn need to be updated when the window scrolls, is resized, or the user enters / exits VR mode.

Hope it's okay! 😁

### CODE REVIEW

**Comment by UXVirtual** [comment]
+1 for this. I'm currently loading a-frame offset from the top of the browser window and I can confirm this PR fixes the issues I was having.

**Comment by mayognaise** [comment]
Ohh I can't believe I didn't notice this till now.
Will check it tonight and merge it. Thank you for the improvement!!

**Comment by toychicken** [comment]
Happy to help 🍻

**Comment by riw** [comment]
hi
there is still a little bug in __getPosition. please use clientX and clientY for touch events, too.

**Comment by mayognaise** [comment]
@riw good catch, I'll debug it and will publish in npm soon.
thank you so much!

**Comment by mayognaise** [comment]
@toychicken @riw @HAZARDU5 thank you for being patient...
im super slow as turtle 🐢 
it's finally on npm!
https://www.npmjs.com/package/aframe-mouse-cursor-component

**Pull request merged**
